### ISSUE TITLE
Make better communication

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#35]
From a user:

I just stumbled upon this; https://dnsimple.com/ — and I thought what an excellent example of communication, something similar would work well for Indiehosters. A few pointers that appealed to me:

"You want to register a domain and set it up with as little effort as possible.”

"We know. We've figured out the hard parts of domain management, so you don't have to worry about them.”

"Made by real people”

"DNSimple is operated by small team of developers, not a giant faceless corporation. “

Additionally “what you get” sort of super simple lists would help indiehosters.net to be more clear. Now it has quite a lot of very technical stuff although you’re not targeting devs, but simple people who just want to have a blog or whatnot and not to pay corporations do get it.

**Comment by michielbdejong** [comment]
I think we're doing quite well on that front with the 'pitch' part. only after the call to action it gets a bit confusing - what exactly is the difference between 'Products we offer' and 'Applications we offer'? And the layout of 'We host FOSS like nobody' is wrong (it's flushed all the way to the left).

But otherwise, I think it's OK. At least we removed the part about infrastructure, and we talk about what we offer, and where to click if you want it. :)

**Comment by pierreozoux** [comment]
IMHO, a product is targeted to non geek people.
Like, one of our "product" is `publishing` (Could be replaced by `blog`, `website` or `site`). And this is what some people are looking for, just a product. They don't even want to bother, what is wordpress.
And an application is for people that are looking for wordpress specifically.

I'm not sure it is well made yet, but IMHO, it should be our goal. We could actually move applications to another page, to make the landing page more user friendly.

I also love the work that (withknown)[https://withknown.com/] did, it is really easy to understand what it is for!

We have to make better job! At least, geeks understand more or less what we are trying to build, and that is nice :)

**Comment by pierreozoux** [comment]
fixed
