### ISSUE TITLE
Add storage limit

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#36]
In the faq:
15GB included with the 8euros/month (10 to 20 GB)
then, it is 0.03euros/GB/month

**Comment by michielbdejong** [comment]
we should use softer wording though, like the original iPod ad said "a thousand songs in your pocket" so it talked about songs where all existing mp3 player manufacturers were talking about megabytes this, megabytes that. Let's do:

* How big is my server?
Big enough for use as a personal server. In case your blog gets a lot of traffic (like if you are a famous celebrity), or you store a lot of big video files on your server (rule of thumb: more than 10 Gb), it could in rare cases happen that you cost your hoster more than what you pay. If this happens, you will be contacted by your hoster, and you will be offered the choice of either reducing your usage, migrating to a different hoster, or paying for the overage at cost price (so whatever  your hoster pays to their supplier).

**Comment by pierreozoux** [comment]
Ok, fixed

**Comment by michielbdejong** [comment]
Oh, forgot to mention, since we had this discussion, one of my customers asked for a 300Gb ownCloud instance. He currently has DNR+DNS+TLS+mailforwarding+WordPress+ownCloud for 8 euros/month. I offered him the option to move to a dedicated 320Gb or 640Gb SATA vps with backups from Vultr.com at cost price. Cost price for these servers is currently 8 usd/month and 15 usd/month. Backups are 1 usd/month in both cases. So the price structure I offered was:

basic package: 8 euros/month (and you can use up to 1 or 2 Gb)
add-on dedicated 320Gb server: 8.50 eur/month
add-on dedicated 640Gb server: 15 eur/month

So in the end he will either pay 8+8.50 = 16.50 eur/month or 8+15 = 23 eur/month

**Comment by pierreozoux** [comment]
Ah ok,so it is kind of 8euros for your work and cost price for the rest, not that bad :)

**Comment by michielbdejong** [comment]
No, my extra work is for free. Those 8 euros are the standard 8 euros which everybody pays, for everything which I consider a "normal" personal server, with a "normal" domain name extension, a "normal" application, a "normal" amount of traffic, and "normal" storage requirements.

And for special requests like this, I basically apply the following rules:

* if I can easily give it to you, I will (for free).
* if it will be too complicated (like the question about mailinglist hosting we had the other day), I'll try to help you find someone who can do it for you (for free).
* if I can do it but it's a bit of extra work, I'll do it if and when I have time (for free).
* if it requires extra hardware usage, I'll bill the cost of that to you (without commission).
